"""add system sender

Revision ID: 3bdc6f7f0916
Revises: 47807cbbfc75
Create Date: 2025-12-31 13:09:35.241861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bdc6f7f0916'
down_revision: Union[str, Sequence[str], None] = '47807cbbfc75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # There was no data at this point so migration done directly
    op.execute(
        "ALTER TYPE message_sender ADD VALUE IF NOT EXISTS 'system';"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # Enum value additions cannot be safely downgraded in PostgreSQL.
    # ### end Alembic commands ###
